CC = g++
CPPFLAGS = -g -Wall
all: main
main: main.o algorithms.o DiskScheduling.o
main.o: main.cpp
algorithms.o: algorithms.cpp
DiskScheduling.o: DiskScheduling.cpp
clean:
	rm -f *.o main
remove:
	rm -f *.o
